### ISSUE TITLE
微信web开发者工具v0.22.202200

### ISSUE THREAD

**Issue by hutualive** [Jeff2Ma/WeApp-Workflow#1]
最新的微信web开发者工具v0.22.202200不工作，报错找不到page/index/index.wxml
同时也不能把整个project.config.json所在的目录直接添加进去，会报错找不到app.js，还是只能添加dist目录
环境是Mac，按照readme操作

**Comment by Jeff2Ma** [comment]
你好，请自行检查下哈，最新版的微信web 开发者工具版本是：1.01.170901
