### ISSUE TITLE
gulp-qcloud-upload 已经不能使用了，麻烦更新一下

### ISSUE THREAD

**Issue by xianyuxmu** [Jeff2Ma/WeApp-Workflow#11]
上传图片会返回“ERROR_PROXY_AUTH_FAILED”报错，原因是签名不合法

**Comment by xianyuxmu** [comment]
gulp-qcloud-upload使用的是qos-node-client，目前基本没人维护了！推荐使用 [TabSpace/gulp-qcloud-cos-upload](https://github.com/TabSpace/gulp-qcloud-cos-upload)替代gulp-qcloud-upload，直接适配腾讯云官方的SDK：[cos-nodejs-sdk-v5](https://github.com/tencentyun/cos-nodejs-sdk-v5)😎😎😎

**Comment by xianyuxmu** [comment]
gulp-qcloud-upload使用的是qos-node-client，目前基本没人维护了！推荐使用 [TabSpace/gulp-qcloud-cos-upload](https://github.com/TabSpace/gulp-qcloud-cos-upload)替代gulp-qcloud-upload，直接适配腾讯云官方的SDK：[cos-nodejs-sdk-v5](https://github.com/tencentyun/cos-nodejs-sdk-v5)😎😎😎

**Comment by Jeff2Ma** [comment]
经过测试，gulp-qcloud-upload 依然正常。应该是你配置或网络问题。

**Comment by xianyuxmu** [comment]
@Jeff2Ma 👌
